# Generated by Django 5.0.3 on 2025-03-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(db_comment='id', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, db_comment='城市名', max_length=200, null=True, verbose_name='城市名')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'db_table': 'app_city',
                'db_table_comment': '城市表',
            },
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(db_comment='id', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, db_comment='机房名', max_length=200, null=True, verbose_name='机房名')),
                ('city', models.ForeignKey(blank=True, db_comment='关联城市', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.city')),
            ],
            options={
                'verbose_name': 'Datacenter',
                'verbose_name_plural': 'Datacenter',
                'db_table': 'app_datacenter',
                'db_table_comment': '机房表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(db_comment='id', primary_key=True, serialize=False, verbose_name='id')),
                ('ip_address', models.CharField(blank=True, db_comment='ip地址', max_length=200, null=True, verbose_name='ip地址')),
                ('status', models.BigIntegerField(db_comment='状态', verbose_name='状态')),
                ('datacenter', models.ForeignKey(blank=True, db_comment='关联机房', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.datacenter')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Host',
                'db_table': 'app_host',
                'db_table_comment': '主机表',
            },
        ),
    ]
