# Generated by Django 5.0.3 on 2025-03-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCount',
            fields=[
                ('id', models.BigAutoField(db_comment='id', primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.IntegerField(blank=True, db_comment='主机数量', null=True, verbose_name='主机数量')),
                ('create_datetime', models.DateTimeField(blank=True, db_comment='创建时间', null=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(blank=True, db_comment='关联城市', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.city')),
                ('datacenter', models.ForeignKey(blank=True, db_comment='关联机房', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.datacenter')),
            ],
            options={
                'verbose_name': 'Host Count',
                'verbose_name_plural': 'Host Count',
                'db_table': 'app_host_count',
                'db_table_comment': '主机数量表',
            },
        ),
    ]
